// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNhWiUxm5Zlm5WjNJ4CsH86ISHgDAas4U',
    appId: '1:461839738913:web:3cb90b501664dc549a1b60',
    messagingSenderId: '461839738913',
    projectId: 'facultyreservation',
    authDomain: 'facultyreservation.firebaseapp.com',
    storageBucket: 'facultyreservation.appspot.com',
    measurementId: 'G-R21F1YR85R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZD50L3hmGNbZgmmh3enNoIHyTNilaSEQ',
    appId: '1:461839738913:android:aa87a18abeaa7cf89a1b60',
    messagingSenderId: '461839738913',
    projectId: 'facultyreservation',
    storageBucket: 'facultyreservation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv8khrLb6VkAaFlAiTGs9p7_mmIDVLK3A',
    appId: '1:461839738913:ios:8473793d87f9e1709a1b60',
    messagingSenderId: '461839738913',
    projectId: 'facultyreservation',
    storageBucket: 'facultyreservation.appspot.com',
    iosBundleId: 'com.example.facultyreservation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv8khrLb6VkAaFlAiTGs9p7_mmIDVLK3A',
    appId: '1:461839738913:ios:b029fc9b7d2bf0489a1b60',
    messagingSenderId: '461839738913',
    projectId: 'facultyreservation',
    storageBucket: 'facultyreservation.appspot.com',
    iosBundleId: 'com.example.facultyreservation.RunnerTests',
  );
}
